/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuoteStatus = IDL.Variant({
  'new' : IDL.Null,
  'pending' : IDL.Null,
  'finalized' : IDL.Null,
  'contacted' : IDL.Null,
});
export const QuoteRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : QuoteStatus,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'monthlyQuantity' : IDL.Text,
  'businessName' : IDL.Text,
  'businessType' : IDL.Text,
  'email' : IDL.Text,
  'brandingNotes' : IDL.Text,
  'submissionTime' : IDL.Int,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllQuotes' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuoteRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'updateQuoteStatus' : IDL.Func([IDL.Nat, QuoteStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuoteStatus = IDL.Variant({
    'new' : IDL.Null,
    'pending' : IDL.Null,
    'finalized' : IDL.Null,
    'contacted' : IDL.Null,
  });
  const QuoteRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : QuoteStatus,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'monthlyQuantity' : IDL.Text,
    'businessName' : IDL.Text,
    'businessType' : IDL.Text,
    'email' : IDL.Text,
    'brandingNotes' : IDL.Text,
    'submissionTime' : IDL.Int,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllQuotes' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuoteRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'updateQuoteStatus' : IDL.Func([IDL.Nat, QuoteStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };