/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface QuoteRequest {
  'id' : bigint,
  'status' : QuoteStatus,
  'city' : string,
  'name' : string,
  'monthlyQuantity' : string,
  'businessName' : string,
  'businessType' : string,
  'email' : string,
  'brandingNotes' : string,
  'submissionTime' : bigint,
  'phone' : string,
}
export type QuoteStatus = { 'new' : null } |
  { 'pending' : null } |
  { 'finalized' : null } |
  { 'contacted' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllQuotes' : ActorMethod<[], Array<QuoteRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuoteRequest' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    bigint
  >,
  'updateQuoteStatus' : ActorMethod<[bigint, QuoteStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];